In [1]:
# from Feat_eng import Y_train, X_train, Y_test, X_test, c1_train, c2_train, c3_train, c1_test, c2_test, c3_test, Y_c1train, Y_c2train, Y_c3train, Y_c1test, Y_c2test ,Y_c3test

In [1]:
import pickle
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, GridSearchCV, KFold, cross_val_score, RandomizedSearchCV
from datetime import datetime
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
import statsmodels.api as sm
import pylab as py
import scipy.stats as stats 
from scipy.stats import norm, skew, probplot
from sklearn.metrics import r2_score, mean_squared_error, accuracy_score
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet, RidgeCV, LassoCV, ElasticNetCV
from sklearn.decomposition import PCA
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import RandomForestRegressor

In [2]:
from Pred_ZRI_feats import zip_test, zip_train, future_feats, future_targets, Y_train, X_train, Y_test, X_test, c1_train, c2_train, c3_train, c1_test, c2_test, c3_test, Y_c1train, Y_c2train, Y_c3train, Y_c1test, Y_c2test ,Y_c3test, target

/Users/jonahwork/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:1637: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)
/Users/jonahwork/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
/Users/jonahwork/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
/Users/jonahwork/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
/Users/jonahwork/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
/Users/jonahwork/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
/Users/jonahwork/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
/Users/jonahwork/Documents/CapstoneFinal/Pred_ZRI_feats.py:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_comb3_red['log_zri'] = np.log(df_comb3_red['zri'])
/Users/jonahwork/Documents/CapstoneFinal/Pred_ZRI_feats.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_comb3_red['log_zori'] = np.log(df_comb3_red['zori'])
/Users/jonahwork/Documents/CapstoneFinal/Pred_ZRI_feats.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_comb3_red['year'] = df_comb3_red['year'] - 2013
/Users/jonahwork/Documents/CapstoneFinal/Pred_ZRI_feats.py:52: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test3['zri_pred'][test3['year']==1] = (test3['zri']*0.049357)+test3['zri']
/Users/jonahwork/Documents/CapstoneFinal/Pred_ZRI_feats.py:104: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  zri_2020['zri'] = (zri_2019[['future_value']]*0.003800)+zri_2019[['future_value']]
/Users/jonahwork/Documents/CapstoneFinal/Pred_ZRI_feats.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  zri_2021['zri'] = (zri_2020[['zri']]*0.024881)+zri_2020[['zri']]
/Users/jonahwork/Documents/CapstoneFinal/Pred_ZRI_feats.py:200: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  feat2_2019[col] = features_2018[col]*test5[col] + features_2018[col]
/Users/jonahwork/Documents/CapstoneFinal/Pred_ZRI_feats.py:201: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  feat2_2019['year'] = 2019
/Users/jonahwork/Documents/CapstoneFinal/Pred_ZRI_feats.py:207: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  feat_2020[col] = (features_2018[col]*(test5[col]*2)) + features_2018[col]
/Users/jonahwork/Documents/CapstoneFinal/Pred_ZRI_feats.py:208: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  feat_2020['year'] = 2020
/Users/jonahwork/Documents/CapstoneFinal/Pred_ZRI_feats.py:214: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  feat_2021[col] = (features_2018[col]*(test5[col]*3)) + features_2018[col]
/Users/jonahwork/Documents/CapstoneFinal/Pred_ZRI_feats.py:215: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  feat_2021['year'] = 2021
/Users/jonahwork/Documents/CapstoneFinal/Pred_ZRI_feats.py:243: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  future_feats['value'] = np.exp(future_feats['log_value'])

In [3]:
target

,RegionName,year,value,geo_id,nonfamily_households,family_households,median_year_structure_built,rent_burden_not_computed,rent_over_50_percent,rent_40_to_50_percent,...,log_value,future_value,male_ratio,white_ratio,black_ratio,asian_ratio,hispanic_ratio,employed_ratio,civil_labor_ratio,Cluster
0,01104,2014,946.100000,01104,3346.0,5526.0,1949.0,158.0,1597.0,523.0,...,6.852348,972.583333,0.477361,0.329594,0.117433,0.010904,0.531703,0.395109,0.469239,1
1,01104,2015,972.583333,01104,3377.0,5407.0,1948.0,146.0,1791.0,466.0,...,6.879956,1058.666667,0.478263,0.319353,0.101512,0.019630,0.549670,0.398254,0.461912,1
2,01104,2016,1058.666667,01104,3432.0,5434.0,1949.0,172.0,1898.0,516.0,...,6.964766,1129.166667,0.467110,0.315878,0.079972,0.017987,0.571669,0.392658,0.449424,1
3,01104,2017,1129.166667,01104,3287.0,5702.0,1946.0,107.0,2032.0,577.0,...,7.029235,1125.083333,0.460292,0.292194,0.078781,0.012735,0.596573,0.388238,0.438968,1
4,01104,2018,1125.083333,01104,3478.0,5599.0,1946.0,75.0,1963.0,502.0,...,7.025612,1145.583333,0.463101,0.275423,0.086447,0.013905,0.604750,0.391816,0.436003,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6042,98499,2014,979.000000,98499,5610.0,6870.0,1973.0,265.0,2355.0,952.0,...,6.886532,995.833333,0.492245,0.467639,0.103251,0.086748,0.211496,0.397328,0.469392,1
6043,98499,2015,995.833333,98499,5736.0,6891.0,1973.0,346.0,2355.0,816.0,...,6.903580,1036.166667,0.505450,0.463689,0.108836,0.087294,0.221283,0.396388,0.464463,1
6044,98499,2016,1036.166667,98499,5670.0,6965.0,1973.0,310.0,2352.0,995.0,...,6.943283,1154.833333,0.502808,0.439341,0.120046,0.093177,0.210382,0.403395,0.459354,1
6045,98499,2017,1154.833333,98499,5149.0,7244.0,1973.0,327.0,2367.0,1006.0,...,7.051711,1257.416667,0.510771,0.425098,0.124402,0.108897,0.206512,0.412859,0.463662,1
6046,98499,2018,1257.416667,98499,5408.0,7539.0,1972.0,458.0,2229.0,963.0,...,7.136815,1305.181818,0.512198,0.433982,0.128706,0.091343,0.213517,0.417750,0.455433,1

In [4]:
future_feats.shape

(2574, 137)

In [5]:
future_targets.shape

(2574, 3)

In [6]:
future_feats

,year,nonfamily_households,family_households,median_year_structure_built,rent_burden_not_computed,rent_over_50_percent,rent_40_to_50_percent,rent_35_to_40_percent,rent_30_to_35_percent,rent_25_to_30_percent,...,est,log_value,male_ratio,white_ratio,black_ratio,asian_ratio,hispanic_ratio,employed_ratio,civil_labor_ratio,Cluster
0,2019,3514.005750,5619.596240,1945.251283,64.221758,2069.917185,500.311260,181.584777,552.064005,465.324405,...,504.060577,7.069693,0.459636,0.263420,0.080712,0.015700,0.624568,0.391020,0.428081,1
1,2020,3550.011500,5640.192481,1944.502565,53.443516,2176.834370,498.622521,161.169554,608.128010,440.648811,...,500.121154,7.113774,0.456172,0.251416,0.074977,0.017495,0.644386,0.390223,0.420160,1
2,2021,3586.017251,5660.788721,1943.753848,42.665274,2283.751555,496.933781,140.754331,664.192015,415.973216,...,496.181731,7.157854,0.452707,0.239413,0.069242,0.019291,0.664204,0.389427,0.412239,1
3,2019,3370.873725,6619.614626,0.000000,311.662957,2014.843245,729.487100,354.197443,677.049498,760.454862,...,248.656208,7.084782,0.478647,0.295612,0.161785,0.047261,0.467141,0.421469,0.459697,1
4,2020,3409.747451,6693.229251,0.000000,344.325913,2032.686491,782.974201,379.394886,696.098996,808.909725,...,246.312417,7.092137,0.479053,0.284688,0.162744,0.046371,0.481499,0.424769,0.457455,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2569,2020,3839.149961,7492.102714,1972.000254,207.124040,647.776627,379.302655,415.846214,846.355676,769.799947,...,330.828118,7.349357,0.490387,0.574766,0.123798,0.083781,0.115791,0.453177,0.460586,1
2570,2021,3756.724942,7609.154072,1972.000381,210.686060,575.664940,377.453983,433.269321,922.533514,858.199920,...,341.242176,7.422146,0.491915,0.569195,0.130759,0.084051,0.116907,0.463085,0.463251,1
2571,2019,5366.584888,7717.252494,1971.750127,533.233881,2199.355425,973.789775,615.147082,906.323242,874.294928,...,1268.491165,7.200888,0.517350,0.426119,0.136041,0.093197,0.214187,0.423036,0.452032,1
2572,2020,5325.169777,7895.504988,1971.500253,608.467762,2169.710849,984.579549,635.294164,988.646483,905.589855,...,1274.982330,7.264961,0.522501,0.418256,0.143377,0.095051,0.214856,0.428323,0.448631,1
2573,2021,5283.754665,8073.757481,1971.250380,683.701644,2140.066274,995.369324,655.441246,1070.969725,936.884783,...,1281.473495,7.329035,0.527653,0.410392,0.150712,0.096905,0.215526,0.433609,0.445231,1

In [5]:
with open("Pickle_lasso_all.pkl" , 'rb') as file:  
     lasso_all = pickle.load(file)

In [6]:
with open("Pickle_lasso_all_PCA.pkl" , 'rb') as file:  
     lasso_all_PCA = pickle.load(file)

In [7]:
with open("Pickle_lasso_c1.pkl" , 'rb') as file:  
     lasso_c1 = pickle.load(file)

In [8]:
with open("Pickle_lasso_c1_PCA.pkl" , 'rb') as file:  
     lasso_c1_PCA = pickle.load(file)

In [9]:
with open("Pickle_lasso_c2.pkl" , 'rb') as file:  
     lasso_c2 = pickle.load(file)

In [10]:
with open("Pickle_lasso_c2_PCA.pkl" , 'rb') as file:  
     lasso_c2_PCA = pickle.load(file)

In [11]:
with open("Pickle_lasso_c3.pkl" , 'rb') as file:  
     lasso_c2 = pickle.load(file)

In [12]:
with open("Pickle_lasso_c3_PCA.pkl" , 'rb') as file:  
     lasso_c2_PCA = pickle.load(file)

In [11]:
with open("rf_all.pkl" , 'rb') as file:  
     rf_all = pickle.load(file)

In [14]:
list(future_feats.isnull().sum())

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [20]:
list(zip(future_feats.columns, list(future_feats.max())))

[('year', 2021.0),
 ('nonfamily_households', 24961.959410419437),
 ('family_households', 39191.43550797895),
 ('median_year_structure_built', 2017.7311023079146),
 ('rent_burden_not_computed', 2848.4269941944117),
 ('rent_over_50_percent', 12073.40810342431),
 ('rent_40_to_50_percent', 3186.730045744383),
 ('rent_35_to_40_percent', 2460.3496850851934),
 ('rent_30_to_35_percent', inf),
 ('rent_25_to_30_percent', 3899.5252270303718),
 ('rent_20_to_25_percent', 4483.325450814269),
 ('rent_15_to_20_percent', 4376.319911928115),
 ('rent_10_to_15_percent', inf),
 ('rent_under_10_percent', inf),
 ('total_pop', 148814.68682023592),
 ('median_age', 62.158737450659274),
 ('commuters_by_public_transportation', inf),
 ('households', 46486.47985255736),
 ('median_income', 179693.74810481275),
 ('income_per_capita', 157709.9979141879),
 ('housing_units', 50209.35217695162),
 ('vacant_housing_units', 12429.59346359319),
 ('vacant_housing_units_for_rent', inf),
 ('median_rent', 3743.7767035882207),
 ('percent_income_spent_on_rent', 56.855114198340374),
 ('owner_occupied_housing_units', 32971.764744078144),
 ('mortgaged_housing_units', 23584.105942116825),
 ('families_with_young_children', 13286.289342969892),
 ('two_parent_families_with_young_children', 12076.58170840527),
 ('two_parents_in_labor_force_families_with_young_children', 8082.10194267406),
 ('two_parents_father_in_labor_force_families_with_young_children', inf),
 ('one_parent_families_with_young_children', inf),
 ('commute_10_14_mins', 9017.749814319168),
 ('commute_15_19_mins', 11639.45714182798),
 ('commute_20_24_mins', 12481.479478534964),
 ('commute_25_29_mins', 8776.664135731648),
 ('commute_30_34_mins', 22083.730172806663),
 ('commute_45_59_mins', 17370.672308171957),
 ('aggregate_travel_time_to_work', 2488265.5960397497),
 ('renter_occupied_housing_units_paying_cash_median_gross_rent',
  3870.59521814631),
 ('owner_occupied_housing_units_lower_value_quartile', 1819527.6743576368),
 ('owner_occupied_housing_units_median_value', 2857143.428571857),
 ('owner_occupied_housing_units_upper_value_quartile', 3500000.2500007497),
 ('married_households', 34562.335129526786),
 ('occupied_housing_units', 46486.47985255736),
 ('housing_units_renter_occupied', 35337.40304588087),
 ('dwellings_1_units_detached', inf),
 ('dwellings_1_units_attached', inf),
 ('dwellings_2_units', inf),
 ('dwellings_3_to_4_units', inf),
 ('dwellings_5_to_9_units', inf),
 ('dwellings_10_to_19_units', inf),
 ('dwellings_20_to_49_units', inf),
 ('dwellings_50_or_more_units', 30537.828765284976),
 ('housing_built_2005_or_later', inf),
 ('housing_built_2000_to_2004', inf),
 ('housing_built_1939_or_earlier', inf),
 ('white_including_hispanic', 98480.52265261908),
 ('black_including_hispanic', 90476.23076696585),
 ('amerindian_including_hispanic', inf),
 ('asian_including_hispanic', 62146.88205048349),
 ('commute_5_9_mins', 5065.20242670866),
 ('commute_35_39_mins', inf),
 ('commute_40_44_mins', inf),
 ('commute_60_89_mins', 15872.007481669309),
 ('commute_90_more_mins', inf),
 ('households_retirement_income', 6978.953062478464),
 ('not_in_labor_force', 34600.32623779995),
 ('bachelors_degree_2', 31596.92102855022),
 ('bachelors_degree_or_higher_25_64', 49896.4649057677),
 ('children', 48965.47393182934),
 ('children_in_single_female_hh', 16020.58593945236),
 ('commuters_by_bus', inf),
 ('commuters_by_car_truck_van', 57233.56075312274),
 ('commuters_by_carpool', 6627.986972616732),
 ('commuters_drove_alone', 51633.58919154599),
 ('different_house_year_ago_different_city', 17711.146959793914),
 ('different_house_year_ago_same_city', inf),
 ('employed_arts_entertainment_recreation_accommodation_food',
  13488.066493410115),
 ('employed_construction', 9023.999768996771),
 ('employed_education_health_social', 22246.42422293728),
 ('employed_finance_insurance_real_estate', 9022.013192665892),
 ('employed_information', 6054.7467198722625),
 ('employed_manufacturing', 10131.929788255982),
 ('employed_other_services_not_public_admin', inf),
 ('employed_public_administration', 7824.583639256924),
 ('employed_retail_trade', 7112.530504802483),
 ('employed_science_management_admin_waste', 15880.135771204936),
 ('employed_transportation_warehousing_utilities', 7520.144714575745),
 ('employed_wholesale_trade', inf),
 ('gini_index', 0.6844067825566559),
 ('graduate_professional_degree', 27054.55731680264),
 ('high_school_including_ged', 31251.677398558175),
 ('households_public_asst_or_food_stamps', 17178.830608979973),
 ('in_grades_1_to_4', inf),
 ('in_grades_5_to_8', 13546.67175457111),
 ('in_grades_9_to_12', inf),
 ('in_school', 51236.468867577976),
 ('in_undergrad_college', 30357.03039061965),
 ('less_than_high_school_graduate', 36964.325551201684),
 ('management_business_sci_arts_employed', 44502.21575218783),
 ('not_us_citizen_pop', 43029.58326976798),
 ('occupation_management_arts', 44502.21575218783),
 ('occupation_natural_resources_construction_maintenance', inf),
 ('occupation_production_transportation_material', 17668.57250045938),
 ('occupation_sales_office', 15837.477051744985),
 ('occupation_services', 22001.71516175818),
 ('poverty', 37027.85225653342),
 ('sales_office_employed', 15837.477051744985),
 ('some_college_and_associates_degree', 26337.429548257867),
 ('walked_to_work', inf),
 ('worked_at_home', 9187.198823584393),
 ('workers_16_and_over', 65303.80622287969),
 ('associates_degree', 8434.237273156738),
 ('bachelors_degree', 31596.92102855022),
 ('high_school_diploma', 26754.39984283138),
 ('less_one_year_college', 10360.255448135718),
 ('masters_degree', 18602.626137509964),
 ('one_year_more_college', 15211.41988878922),
 ('commute_35_44_mins', 11764.796901819418),
 ('commute_60_more_mins', 22040.253529328358),
 ('commute_less_10_mins', 6213.706241399525),
 ('commuters_16_over', 61121.12287716281),
 ('hispanic_any_race', 103490.32935603613),
 ('cpi', 350.2599395583071),
 ('gdp', 5.907295891062008),
 ('interest', 7.799858653075569),
 ('est', 7257.649827634939),
 ('log_value', 8.449144079272088),
 ('male_ratio', 0.6387721037908661),
 ('white_ratio', 0.8960632863830662),
 ('black_ratio', 0.9807036659624351),
 ('asian_ratio', 0.747908986253294),
 ('hispanic_ratio', 0.9736452638809286),
 ('employed_ratio', 0.7963565209550042),
 ('civil_labor_ratio', 0.8210561909514664),
 ('Cluster', 2.0)]

In [8]:
future_feats_2020 = future_feats[future_feats['year']==2020]

In [9]:
future_targets_2021 = future_targets[future_targets['year']==2021]

In [12]:
print(rf_all.best_params_)
print(rf_all.best_score_)
Y_pred = rf_all.predict(future_feats_2020)
pred_unlog = np.exp(Y_pred)
Y_unlog = future_targets_2021[['ZRI']]
train_RMSE = np.sqrt(mean_squared_error(Y_unlog, pred_unlog))
print('The RMSE is:', train_RMSE)

{'n_estimators': 19, 'min_samples_split': 2, 'min_samples_leaf': 7, 'max_samples': 0.7}
0.9787581366670949
The RMSE is: 155.6823800441864

In [13]:
Y_pred_test = np.exp(rf_all.predict(X_test))

In [14]:
Y_actual = np.exp(Y_test)

In [15]:
zip_test

    RegionName         City
0        01104  Springfield
1        01108  Springfield
2        01109  Springfield
3        01602    Worcester
4        01603    Worcester
..         ...          ...
920      98125      Seattle
921      98201      Everett
922      98203      Everett
923      98498     Lakewood
924      98499     Lakewood

[925 rows x 2 columns]

In [16]:
diff_df = pd.DataFrame()

In [17]:
diff_df['Zip'] = zip_test['RegionName']
diff_df['City'] = zip_test['City']
diff_df['Pred'] = Y_pred_test
diff_df['Act'] = np.exp(Y_test)

In [18]:
diff_df['Model_Error'] = diff_df['Pred'] - diff_df['Act']

In [19]:
diff_df

       Zip         City         Pred          Act  Model_Error
0    01104  Springfield  1150.714148  1145.583333     5.130815
1    01108  Springfield  1192.499645  1201.500000    -9.000355
2    01109  Springfield  1171.390547  1196.727273   -25.336726
3    01602    Worcester  1462.432603  1401.333333    61.099270
4    01603    Worcester  1324.319494  1325.583333    -1.263839
..     ...          ...          ...          ...          ...
920  98125      Seattle  1761.159632  1645.200000   115.959632
921  98201      Everett  1454.265146  1450.916667     3.348480
922  98203      Everett  1519.896025  1510.916667     8.979359
923  98498     Lakewood  1373.151584  1409.000000   -35.848416
924  98499     Lakewood  1282.105103  1305.181818   -23.076715

[925 rows x 5 columns]

In [21]:
comparison = pd.DataFrame()

In [22]:
comparison['Zip'] = future_targets_2021['RegionName']

In [23]:
comparison['Year'] = future_targets_2021['year']

In [24]:
comparison['NoCOVID_ZRI'] = pred_unlog

In [25]:
comparison['COVID_ZRI'] = future_targets_2021[['ZRI']]

In [26]:
comparison['Difference'] = comparison['NoCOVID_ZRI'] - comparison['COVID_ZRI']

In [27]:
comparison = comparison[comparison['Year']==2021]

In [28]:
test = comparison.merge(diff_df, how = 'left', on = 'Zip')

In [29]:
test['Pct'] = (test['Difference'] - test['Model_Error'])/test['Model_Error']

In [35]:
test['Diff_Greater_Than_Error'] = (abs(test['Difference'])>abs(test['Model_Error']))

In [38]:
test['Adjusted_Diff'] = test['Difference'] - test['Model_Error']

In [53]:
test['Pct_Diff'] = test['Adjusted_Diff']/test['NoCOVID_ZRI']

In [54]:
test_true = test[test['Diff_Greater_Than_Error'] == True]

In [57]:
test_true.sort_values(by = 'Pct_Diff').head(20)

,Zip,Year,NoCOVID_ZRI,COVID_ZRI,Difference,City,Pred,Act,Model_Error,Pct,Diff_Greater_Than_Error,Adjusted_Diff,Pct_Diff
832,97232,2021,1601.529341,1691.735657,-90.206316,Portland,1696.388918,1644.416667,51.972251,-2.735663,True,-142.178568,-0.088777
359,32209,2021,797.198911,834.765626,-37.566715,Jacksonville,844.080543,811.416667,32.663877,-2.150100,True,-70.230591,-0.088097
314,27603,2021,1224.936865,1317.861477,-92.924612,Raleigh,1265.614813,1281.000000,-15.385187,5.039875,True,-77.539425,-0.063301
581,77006,2021,1391.992825,1446.887077,-54.894252,Houston,1425.627350,1406.416667,19.210683,-3.857486,True,-74.104935,-0.053237
448,47374,2021,666.685362,690.879935,-24.194572,Richmond,681.265020,671.555556,9.709465,-3.491854,True,-33.904037,-0.050855
276,20009,2021,2206.814309,2450.543355,-243.729045,Washington,2241.659876,2382.000000,-140.340124,0.736703,True,-103.388922,-0.046850
72,10013,2021,4096.851514,4582.633915,-485.782401,New York,4158.944133,4454.454545,-295.510413,0.643876,True,-190.271988,-0.046443
628,78731,2021,1457.496885,1610.875458,-153.378573,Austin,1471.537226,1565.818182,-94.280955,0.626825,True,-59.097617,-0.040547
247,15217,2021,1245.111908,1277.139111,-32.027204,Pittsburgh,1258.270995,1241.416667,16.854329,-2.900236,True,-48.881532,-0.039259
278,20011,2021,1923.188363,2014.248998,-91.060635,Washington,1937.855418,1957.909091,-20.053673,3.540846,True,-71.006962,-0.036921
330,28209,2021,1326.465547,1354.336246,-27.870699,Charlotte,1335.255974,1316.454545,18.801428,-2.482371,True,-46.672127,-0.035185
437,44108,2021,766.873419,788.813651,-21.940233,Cleveland,769.076502,766.750000,2.326502,-10.430568,True,-24.266734,-0.031644
273,20005,2021,2217.066713,2394.989475,-177.922763,Washington,2217.712451,2328.000000,-110.287549,0.613262,True,-67.635214,-0.030507
579,76549,2021,661.039358,709.255009,-48.215651,Killeen,661.039358,689.416667,-28.377308,0.699092,True,-19.838342,-0.030011
236,14611,2021,873.364393,905.579676,-32.215283,Rochester,873.364393,880.250000,-6.885607,3.678641,True,-25.329676,-0.029002
500,60623,2021,1321.740685,1342.895015,-21.154330,Chicago,1321.989152,1305.333333,16.655819,-2.270086,True,-37.810149,-0.028606
274,20007,2021,2116.569481,2212.381816,-95.812335,Washington,2114.729152,2150.500000,-35.770848,1.678503,True,-60.041486,-0.028367
277,20010,2021,2122.735966,2259.362566,-136.626600,Washington,2119.311810,2196.166667,-76.854857,0.777722,True,-59.771743,-0.028158
257,19121,2021,1337.268604,1401.846971,-64.578367,Philadelphia,1335.173375,1362.636364,-27.462989,1.351469,True,-37.115378,-0.027755
275,20008,2021,2056.523720,2141.224840,-84.701120,Washington,2052.147370,2081.333333,-29.185963,1.902118,True,-55.515157,-0.026995

In [56]:
test_true.sort_values(by = 'Pct_Diff', ascending = False).head(20)

,Zip,Year,NoCOVID_ZRI,COVID_ZRI,Difference,City,Pred,Act,Model_Error,Pct,Diff_Greater_Than_Error,Adjusted_Diff,Pct_Diff
543,75034,2021,2219.062987,1685.237225,533.825762,Frisco,1535.308416,1638.100000,-102.791584,-6.193283,True,636.617346,0.286886
803,94602,2021,3401.134242,2738.257583,662.876659,Oakland,2631.470659,2661.666667,-30.196008,-22.952460,True,693.072667,0.203777
824,95816,2021,1884.005793,1624.779515,259.226277,Sacramento,1455.905324,1579.333333,-123.428009,-3.100222,True,382.654287,0.203107
825,95831,2021,1941.569517,1618.263937,323.305580,Sacramento,1562.530555,1573.000000,-10.469445,-31.880871,True,333.775025,0.171910
808,94608,2021,3474.075462,2942.983917,531.091545,Oakland,2798.474457,2860.666667,-62.192210,-9.539519,True,593.283755,0.170775
805,94605,2021,2976.312706,2539.532440,436.780266,Oakland,2407.046460,2468.500000,-61.453540,-8.107487,True,498.233806,0.167400
472,55406,2021,1837.010712,1485.271316,351.739396,Minneapolis,1509.300211,1443.727273,65.572939,4.364094,True,286.166458,0.155778
852,98121,2021,2810.177054,2379.931942,430.245112,Seattle,2307.625440,2313.363636,-5.738197,-75.979149,True,435.983309,0.155144
366,32811,2021,1620.354649,1373.329625,247.025024,Orlando,1332.872035,1334.916667,-2.044632,-121.816380,True,249.069656,0.153713
830,97214,2021,1928.611360,1641.084049,287.527311,Portland,1588.715838,1595.181818,-6.465980,-45.467705,True,293.993292,0.152438
827,97202,2021,1833.573538,1606.105680,227.467858,Portland,1512.253973,1561.181818,-48.927845,-5.649047,True,276.395704,0.150742
471,55404,2021,1626.807576,1405.650323,221.157252,Minneapolis,1350.812948,1366.333333,-15.520385,-15.249470,True,236.677637,0.145486
812,94621,2021,3006.290251,2622.005946,384.284305,Oakland,2503.770941,2548.666667,-44.895726,-9.559485,True,429.180030,0.142761
807,94607,2021,3321.688256,2900.632657,421.055599,Oakland,2781.739387,2819.500000,-37.760613,-12.150656,True,458.816212,0.138127
810,94610,2021,3016.776537,2755.403842,261.372695,Oakland,2527.298632,2678.333333,-151.034701,-2.730547,True,412.407396,0.136705
341,30096,2021,1495.171449,1332.778722,162.392727,Duluth,1254.138660,1295.500000,-41.361340,-4.926196,True,203.754066,0.136275
818,95112,2021,3082.431256,2666.671951,415.759305,San Jose,2589.493798,2592.083333,-2.589536,-161.553615,True,418.348840,0.135720
540,66062,2021,1122.332856,987.967451,134.365405,Olathe,944.989783,960.333333,-15.343550,-9.757126,True,149.708955,0.133391
688,89113,2021,1586.482723,1337.751137,248.731586,Las Vegas,1339.818671,1300.333333,39.485337,5.299341,True,209.246248,0.131893
372,32839,2021,1573.428844,1381.817023,191.611821,Orlando,1327.618768,1343.166667,-15.547899,-13.323969,True,207.159720,0.131661

In [59]:
test_true.sort_values(by = 'Pct_Diff', key = abs, ascending = False).head(20)

,Zip,Year,NoCOVID_ZRI,COVID_ZRI,Difference,City,Pred,Act,Model_Error,Pct,Diff_Greater_Than_Error,Adjusted_Diff,Pct_Diff
543,75034,2021,2219.062987,1685.237225,533.825762,Frisco,1535.308416,1638.100000,-102.791584,-6.193283,True,636.617346,0.286886
803,94602,2021,3401.134242,2738.257583,662.876659,Oakland,2631.470659,2661.666667,-30.196008,-22.952460,True,693.072667,0.203777
824,95816,2021,1884.005793,1624.779515,259.226277,Sacramento,1455.905324,1579.333333,-123.428009,-3.100222,True,382.654287,0.203107
825,95831,2021,1941.569517,1618.263937,323.305580,Sacramento,1562.530555,1573.000000,-10.469445,-31.880871,True,333.775025,0.171910
808,94608,2021,3474.075462,2942.983917,531.091545,Oakland,2798.474457,2860.666667,-62.192210,-9.539519,True,593.283755,0.170775
805,94605,2021,2976.312706,2539.532440,436.780266,Oakland,2407.046460,2468.500000,-61.453540,-8.107487,True,498.233806,0.167400
472,55406,2021,1837.010712,1485.271316,351.739396,Minneapolis,1509.300211,1443.727273,65.572939,4.364094,True,286.166458,0.155778
852,98121,2021,2810.177054,2379.931942,430.245112,Seattle,2307.625440,2313.363636,-5.738197,-75.979149,True,435.983309,0.155144
366,32811,2021,1620.354649,1373.329625,247.025024,Orlando,1332.872035,1334.916667,-2.044632,-121.816380,True,249.069656,0.153713
830,97214,2021,1928.611360,1641.084049,287.527311,Portland,1588.715838,1595.181818,-6.465980,-45.467705,True,293.993292,0.152438
827,97202,2021,1833.573538,1606.105680,227.467858,Portland,1512.253973,1561.181818,-48.927845,-5.649047,True,276.395704,0.150742
471,55404,2021,1626.807576,1405.650323,221.157252,Minneapolis,1350.812948,1366.333333,-15.520385,-15.249470,True,236.677637,0.145486
812,94621,2021,3006.290251,2622.005946,384.284305,Oakland,2503.770941,2548.666667,-44.895726,-9.559485,True,429.180030,0.142761
807,94607,2021,3321.688256,2900.632657,421.055599,Oakland,2781.739387,2819.500000,-37.760613,-12.150656,True,458.816212,0.138127
810,94610,2021,3016.776537,2755.403842,261.372695,Oakland,2527.298632,2678.333333,-151.034701,-2.730547,True,412.407396,0.136705
341,30096,2021,1495.171449,1332.778722,162.392727,Duluth,1254.138660,1295.500000,-41.361340,-4.926196,True,203.754066,0.136275
818,95112,2021,3082.431256,2666.671951,415.759305,San Jose,2589.493798,2592.083333,-2.589536,-161.553615,True,418.348840,0.135720
540,66062,2021,1122.332856,987.967451,134.365405,Olathe,944.989783,960.333333,-15.343550,-9.757126,True,149.708955,0.133391
688,89113,2021,1586.482723,1337.751137,248.731586,Las Vegas,1339.818671,1300.333333,39.485337,5.299341,True,209.246248,0.131893
372,32839,2021,1573.428844,1381.817023,191.611821,Orlando,1327.618768,1343.166667,-15.547899,-13.323969,True,207.159720,0.131661

In [60]:
test_true.sort_values(by = 'Pct_Diff', key = abs).head(20)

,Zip,Year,NoCOVID_ZRI,COVID_ZRI,Difference,City,Pred,Act,Model_Error,Pct,Diff_Greater_Than_Error,Adjusted_Diff,Pct_Diff
627,78729,2021,1306.770677,1291.970625,14.800052,Austin,1270.404639,1255.833333,14.571305,0.015698,True,0.228747,0.000175
525,63104,2021,865.087728,879.345899,-14.258172,Saint Louis,841.052571,854.750000,-13.697429,0.040938,True,-0.560743,-0.000648
53,06513,2021,1304.206095,1275.853142,28.352953,New Haven,1267.163163,1240.166667,26.996496,0.050246,True,1.356457,0.001040
162,11232,2021,2224.998180,2125.278819,99.719361,New York,2163.034525,2065.833333,97.201192,0.025907,True,2.518169,0.001132
450,53204,2021,759.364073,729.659057,29.705016,Milwaukee,738.024586,709.250000,28.774586,0.032335,True,0.930430,0.001225
57,06605,2021,1493.719111,1448.258777,45.460333,Bridgeport,1450.618472,1407.750000,42.868472,0.060461,True,2.591862,0.001735
90,10075,2021,3149.651620,3154.319355,-4.667735,New York,3066.957856,3066.090909,0.866947,-6.384107,True,-5.534682,-0.001757
678,85716,2021,809.852235,776.639807,33.212427,Tucson,785.570112,754.916667,30.653446,0.083481,True,2.558982,0.003160
521,60654,2021,2238.110195,2225.670166,12.440029,Chicago,2168.524640,2163.416667,5.107974,1.435414,True,7.332055,0.003276
495,60618,2021,1760.823892,1690.745850,70.078042,Chicago,1707.603985,1643.454545,64.149439,0.092419,True,5.928603,0.003367
793,93309,2021,1095.253586,1090.159155,5.094430,Bakersfield,1060.952294,1059.666667,1.285627,2.962604,True,3.808803,0.003478
252,19104,2021,1326.342713,1338.351256,-12.008543,Philadelphia,1293.589167,1300.916667,-7.327500,0.638832,True,-4.681044,-0.003529
84,10028,2021,3168.861012,3148.396101,20.464911,New York,3067.744409,3060.333333,7.411076,1.761395,True,13.053835,0.004119
78,10021,2021,3427.094940,3232.241309,194.853631,New York,3322.359139,3141.833333,180.525805,0.079367,True,14.327826,0.004181
354,30342,2021,1516.289411,1580.027779,-63.738368,Sandy Springs,1478.559362,1535.833333,-57.273971,0.112868,True,-6.464397,-0.004263
135,11204,2021,2125.783029,2067.410195,58.372834,New York,2058.540513,2009.583333,48.957179,0.192324,True,9.415655,0.004429
598,77339,2021,1241.327152,1214.422772,26.904380,Houston,1200.574623,1180.454545,20.120078,0.337191,True,6.784303,0.005465
801,94115,2021,3594.317091,3745.085919,-150.768828,San Francisco,3509.726632,3640.333333,-130.606701,0.154373,True,-20.162127,-0.005609
268,19147,2021,1481.762863,1498.583048,-16.820185,Philadelphia,1448.277611,1456.666667,-8.389056,1.005015,True,-8.431129,-0.005690
160,11230,2021,2086.265908,2059.179990,27.085918,New York,2015.871059,2001.583333,14.287726,0.895747,True,12.798192,0.006134

In [58]:
test_true.groupby('City')[['Pct_Diff']].mean().sort_values(by = 'Pct_Diff', ascending = False)

               Pct_Diff
City
Frisco         0.286886
Sacramento     0.187508
Oakland        0.141766
Duluth         0.127380
Minneapolis    0.117184
...                 ...
Alexandria    -0.013929
Silver Spring -0.015072
Pompano Beach -0.016050
Bradenton     -0.024905
Killeen       -0.030011

[108 rows x 1 columns]

In [14]:
with open("rf_all_PCA.pkl" , 'rb') as file:  
     rf_all_PCA = pickle.load(file)

In [15]:
with open("rf_cluster1.pkl" , 'rb') as file:  
     rf_c1 = pickle.load(file)

In [16]:
with open("rf_cluster2.pkl" , 'rb') as file:  
     rf_c1 = pickle.load(file)

In [17]:
with open("rf_cluster3.pkl" , 'rb') as file:  
     rf_c1 = pickle.load(file)